version: "3"
services:
  android_builder:
    build: .
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - /home/${USER}/android/lineage/:/source # SourceCode Directory
      - /home/${USER}/.ccache:/ccache # ccache directory

